version: "3.8"

services:
  app:
    container_name: qa_generator_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT:-4025}:${APP_PORT:-4025}"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - .:/app
      - /app/node_modules # To prevent conflicts between host and container node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # This is to enable polling for file changes, useful for certain Docker environments
